logging:
  level:
    org.springframework.boot.autoconfigure.security: INFO
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: user
      password: user
  datasource:
    url: jdbc:h2:mem:library
    username: sa
    password:
api:
  endpoint:
    base-url: /api/v1
